#!/usr/bin/env perl

use strict;
use warnings;
use POSIX qw/strftime/;

my $click   = $ENV{BLOCK_BUTTON} || 0;
my $format  = $ENV{BLOCK_INSTANCE};

my @tz_list = (
  "Australia/Melbourne",
  "Asia/Shanghai",
  "Europe/London",
  "America/New_York",
  "America/Chicago",
  "America/Los_Angeles"
);
my @tz_labels = (
  "",
  "China",
  "London",
  "EST",
  "CST",
  "PST"
);

my $current_tz = 0;
if ($ENV{_tz}) {
  ($current_tz) = grep { $tz_list[$_] eq $ENV{_tz} } 0 .. $#tz_list;
}
if ($click == 1) {
  $current_tz = ($current_tz + 1) % scalar @tz_list;
}

my $text = $format ? strftime($format, localtime()) : localtime();
if ($current_tz != 0) {
  $text = "$text ($tz_labels[$current_tz])";
}
print "{\"full_text\":\"$text\",\"_tz\":\"$tz_list[$current_tz]\"}\n"
