#!/usr/bin/sh -e

# This defaults to the current default sink
SINK="${BLOCK_INSTANCE:-$(pactl get-default-sink)}"

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-2%}"

#------------------------------------------------------------------------

volume() {
    pactl list sinks | awk "/Name:/{
        def = \$2 == \"${SINK}\"
    }/Mute:/ && def{
        mut = \$2 == \"yes\"
    }/^\s*Volume:/ && def{
        vol = \$5
    }END{
        if (mut) {printf \"muted (%s)\", vol} else {print vol}
    }"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) pactl set-sink-mute "${SINK}" toggle ;;  # right click, mute/unmute
  4) pactl set-sink-volume "${SINK}" "+${STEP}" ;; # scroll up, increase
  5) pactl set-sink-volume "${SINK}" "-${STEP}" ;; # scroll down, decrease
esac

volume
echo
